version: "3.9"

services:

  expenses:
    build: .
    ports:
      - "8080:8080"
    environment:
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      JDBC_URL: jdbc:mysql://mysql:3306/expenses
      JDBC_USER: root
      JDBC_PASSWORD: password
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d