micronaut:
  application:
    name: expenses
  server:
    cors:
      enabled: true
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:expenses;INIT=CREATE SCHEMA IF NOT EXISTS expenses;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
